spring.application.name=plain

# ===============================================
#  VERİTABANI BAĞLANTI AYARLARI (DATASOURCE)
# ===============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/plain_db

spring.datasource.username=postgres

spring.datasource.password=2233


# ===============================================
#  JPA ve HIBERNATE AYARLARI
# ===============================================
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# HTTP istek ve yanıtları için karakter kodlamasını UTF-8 olarak ayarla
server.servlet.encoding.charset=UTF-8
# Bu kodlama yapılandırmasını etkinleştir
server.servlet.encoding.enabled=true
# İstemci belirtmese bile bu kodlamayı zorla
server.servlet.encoding.force=true

# Gelen POST isteklerinin maksimum boyutunu 10MB olarak ayarla
server.tomcat.max-http-form-post-size=10MB

# HTTP istek başlıklarının maksimum boyutunu 64KB olarak ayarla (yeni standart)
spring.servlet.multipart.max-request-size=10MB

# HTTP istek gövdesinin maksimum boyutunu 10MB olarak ayarla (yeni standart)
spring.servlet.multipart.max-file-size=10MB


logging.level.org.springframework.security=DEBUG

